#server:
#  port: 9021
#spring:
#  profiles:
#    active: test1
#---
#spring:
#  config:
#    activate:
#      on-profile: devv
#person:
#  name: chey
#  last-name: bbbbbbb
#  age: 12
#  boss: true
#  birth: 2012/12/12
#  maps: {k1: 2,ks: ss}
#  lists:
#    -sss
#    -112s
#  dog:
#    name: gg
#    age: 22
#---
#spring:
#  config:
#    activate:
#      on-profile: test1
#person:
#  lastName: fffffff
#---
#  spring:
#    config:
#      activate:
#        on-profile: test2
#person:
#  lastName: ggggggg